"""Centralized config from env. Use settings() everywhere instead of os.getenv."""
from functools import lru_cache

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    # .env loading happens via eigen.envloader (python-dotenv with override=True)
    # called from every entry point. Pydantic-settings here only reads os.environ.
    model_config = SettingsConfigDict(env_prefix="EIGEN_", extra="ignore")

    # Storage
    database_url: str = Field("sqlite:///./eigen.db", description="SQLAlchemy URL")
    redis_url: str = Field("redis://localhost:6379/0", description="arq broker / cache")

    # ESP
    esp: str = Field("log", description="log | resend | fake | inbox")
    resend_api_key: str | None = None
    resend_webhook_secret: str | None = Field(None, description="Svix-style HMAC secret")
    sender_from: str = "Eigen <no-reply@example.com>"
    # eigen-inbox URL (when esp=inbox). Dev: http://localhost:8001.
    inbox_url: str = "http://localhost:8001"
    # Shared secret the inbox sends on its webhook callbacks.
    inbox_webhook_secret: str = "dev-secret-change-me"
    # Synthetic clock multiplier applied to scheduler intervals + settle windows.
    # 1.0 = real time. 60.0 = 1 wall-clock second = 1 sim minute.
    time_scale: float = 1.0

    # LLM
    anthropic_api_key: str | None = None
    llm_model: str = "claude-sonnet-4-6"

    # Generator
    generator: str = Field("template", description="template | llm")
    auto_spawn: bool = Field(True, description="auto-promote pending variants generated by research")

    # Worker
    send_mode: str = Field("sync", description="sync (inline) | async (arq queue)")

    # Scheduler
    scheduler_enabled: bool = False
    settle_window_seconds: int = 24 * 3600
    tick_interval_seconds: int = 300

    # Stopping rule
    stop_prob_best: float = 0.95

    # Auth
    api_keys: list[str] = Field(default_factory=list, description="comma-separated EIGEN_API_KEYS")


@lru_cache
def settings() -> Settings:
    return Settings()
