"""campaign status, posteriors, cohorts

Revision ID: 373f97019b84
Revises: 5764b4a1e4a5
Create Date: 2026-05-13 22:42:32.879998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373f97019b84'
down_revision: Union[str, Sequence[str], None] = '5764b4a1e4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posterior',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('cohort', sa.String(length=80), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], name=op.f('fk_posterior_variant_id_variant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posterior')),
    sa.UniqueConstraint('variant_id', 'cohort', name='uq_posterior_variant_cohort')
    )
    with op.batch_alter_table('posterior', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posterior_cohort'), ['cohort'], unique=False)
        batch_op.create_index(batch_op.f('ix_posterior_variant_id'), ['variant_id'], unique=False)

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('stopped_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('stopped_reason', sa.String(length=80), nullable=True))

    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cohort', sa.String(length=80), nullable=False))
        batch_op.create_index(batch_op.f('ix_recipient_cohort'), ['cohort'], unique=False)

    with op.batch_alter_table('send', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cohort', sa.String(length=80), nullable=False))
        batch_op.create_index(batch_op.f('ix_send_cohort'), ['cohort'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_send_cohort'))
        batch_op.drop_column('cohort')

    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipient_cohort'))
        batch_op.drop_column('cohort')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('stopped_reason')
        batch_op.drop_column('stopped_at')
        batch_op.drop_column('status')

    with op.batch_alter_table('posterior', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posterior_variant_id'))
        batch_op.drop_index(batch_op.f('ix_posterior_cohort'))

    op.drop_table('posterior')
    # ### end Alembic commands ###
