"""events: provider id + raw + suppression

Revision ID: 3f4ce16113fa
Revises: 452799e0f7a9
Create Date: 2026-05-13 22:28:36.638330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4ce16113fa'
down_revision: Union[str, Sequence[str], None] = '452799e0f7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppression', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppression_email'), ['email'], unique=True)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('provider_event_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('raw', sa.JSON(), nullable=True))
        batch_op.alter_column('kind',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_event_provider_event', ['provider', 'provider_event_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('uq_event_provider_event', type_='unique')
        batch_op.alter_column('kind',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('raw')
        batch_op.drop_column('provider_event_id')
        batch_op.drop_column('provider')

    with op.batch_alter_table('suppression', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppression_email'))

    op.drop_table('suppression')
    # ### end Alembic commands ###
