"""send: provider + provider_message_id

Revision ID: 452799e0f7a9
Revises: 87c769f98dcd
Create Date: 2026-05-13 22:26:38.876137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452799e0f7a9'
down_revision: Union[str, Sequence[str], None] = '87c769f98dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('send', sa.Column('provider', sa.String(length=40), nullable=True))
    op.add_column('send', sa.Column('provider_message_id', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_send_provider_message_id'), 'send', ['provider_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_send_provider_message_id'), table_name='send')
    op.drop_column('send', 'provider_message_id')
    op.drop_column('send', 'provider')
    # ### end Alembic commands ###
