"""auth: org, api_key, scope campaigns and suppression to org

Revision ID: 5764b4a1e4a5
Revises: 3f4ce16113fa
Create Date: 2026-05-13 22:33:43.543911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5764b4a1e4a5'
down_revision: Union[str, Sequence[str], None] = '3f4ce16113fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org')),
    sa.UniqueConstraint('name', name=op.f('uq_org_name'))
    )
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], name=op.f('fk_api_key_org_id_org')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_key'))
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_key_hash'), ['key_hash'], unique=True)

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_campaign_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_campaign_org_id_org'), 'org', ['org_id'], ['id'])

    with op.batch_alter_table('suppression', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_suppression_email'))
        batch_op.create_index(batch_op.f('ix_suppression_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppression_org_id'), ['org_id'], unique=False)
        batch_op.create_unique_constraint('uq_suppression_org_email', ['org_id', 'email'])
        batch_op.create_foreign_key(batch_op.f('fk_suppression_org_id_org'), 'org', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppression', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_suppression_org_id_org'), type_='foreignkey')
        batch_op.drop_constraint('uq_suppression_org_email', type_='unique')
        batch_op.drop_index(batch_op.f('ix_suppression_org_id'))
        batch_op.drop_index(batch_op.f('ix_suppression_email'))
        batch_op.create_index(batch_op.f('ix_suppression_email'), ['email'], unique=1)
        batch_op.drop_column('org_id')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_campaign_org_id_org'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_campaign_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_key_hash'))

    op.drop_table('api_key')
    op.drop_table('org')
    # ### end Alembic commands ###
