"""decision audit log

Revision ID: 9aad1675cfee
Revises: 373f97019b84
Create Date: 2026-05-13 22:44:48.874758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aad1675cfee'
down_revision: Union[str, Sequence[str], None] = '373f97019b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_decision_campaign_id_campaign')),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], name=op.f('fk_decision_variant_id_variant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision'))
    )
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_campaign_id'))

    op.drop_table('decision')
    # ### end Alembic commands ###
